spring:
  application:
    name: springcloud-apigateway
  cloud:
    gateway:
      routes:
        - id: userservice_route
          predicates:
            - Path=/usergateway/**
          filters:
            - StripPrefix=1
            - SunHong=Hello »ÒÌ«ÀÇ
          uri: http://localhost:8010/
        - id: cookie_route
          predicates:
            - Path=/define/**
            - Auth=Authorization
            #- Cookie=name,sunhong
          uri: https://music.163.com/#/artist?id=3695

server:
  port: 8088

