server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: lb_first
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
            - SunHong=Hello sunhong
          uri: http://localhost:8088/
        - id: lb_cookie
          predicates:
            - Cookie=name,sunhong
          uri: http://dubbo.apache.org/zh-cn/
        - id: my_lb
          predicates:
            - Path=/mypredicate/**
            - Auth=Authorization,123
          filters:
            - StripPrefix=1
          uri: http://dubbo.apache.org/zh-cn/
        - id: lb_route
          predicates:
            - Path=/lb/**
          filters:
            - StripPrefix=1
          uri: lb://ORDER-SERVICE
        - id: ratelimiter_route
          predicates:
            - Path=/ratelimiter/**
          filters:
            - name: RequestRateLimiter
              args:
                deny-empty-key: true
                keyResolver: '#{@ipAddressKeyResolver}'
                redis-rate-limiter.replenishRate: 1

                redis-rate-limiter.burstCapacity: 2
          uri: lb://order-service
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:9091/eureka"


