server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: lb_first
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
          uri: http://localhost:8088/
        - id: lb_cookie
          predicates:
            - Cookie=name,sunhong
          uri: https://www.baidu.com
        - id: my_predicate
          predicates:
            - Path=/mypredicate/**
            - Auth=Authorization
          filtes:
            - StripPrefix=1
          uri: https://www.baidu.com/
